export const projectConfig = {
  launched: false,
  project: {
    name: '',
    organization: '',
    progress: {
      renameOrg: false,
      renameProject: false,
      setup: false,
    },
  },
  infisical: {
    projectId: '',
    organizationId: '',
    organizationSlug: '',
    projectSlug: '',
    configProjectName: '',
    progress: {
      selectOrg: false,
      createProject: false,
      renameEnv: false,
      createApps: false,
      setInheritance: false,
      ensureApiAuthSecrets: false,
    },
    error: '',
  },
  planetscale: {
    organization: '',
    region: '',
    database: '',
    tokenId: '',
    configProjectName: '',
    progress: {
      selectOrg: false,
      selectRegion: false,
      createToken: false,
      setInfisicalToken: false,
      createDB: false,
      renameProductionBranch: false,
      createStagingBranch: false,
      createPasswords: false,
      storeConnectionStrings: false,
      initMigrationTable: false,
      configureDB: false,
    },
    error: '',
  },
  railway: {
    projectId: '',
    workspaceId: '',
    prodEnvironmentId: '',
    stagingEnvironmentId: '',
    prodApiServiceId: '',
    stagingApiServiceId: '',
    prodWorkerServiceId: '',
    stagingWorkerServiceId: '',
    prodRedisServiceId: '',
    stagingRedisServiceId: '',
    prodRedisVolumeId: '',
    stagingRedisVolumeId: '',
    configProjectName: '',
    progress: {
      selectWorkspace: false,
      storeRailwayToken: false,
      createProject: false,
      renameProductionEnv: false,
      createStagingEnv: false,
      createRedisProd: false,
      renameRedisProd: false,
      renameRedisProdVolume: false,
      createRedisStaging: false,
      renameRedisStaging: false,
      renameRedisStagingVolume: false,
      storeRedisUrl: false,
      createInfisicalConnection: false,
      promptedForGithub: false,
      createApiProd: false,
      createInfisicalSyncProd: false,
      connectApiProdGithub: false,
      createApiStaging: false,
      createInfisicalSyncStagingApi: false,
      connectApiStagingGithub: false,
      storeApiUrl: false,
      createWorkerProd: false,
      connectWorkerProdGithub: false,
      createWorkerStaging: false,
      createInfisicalSyncStagingWorker: false,
      connectWorkerStagingGithub: false,
      verifyDeployment: false,
    },
    error: '',
  },
  vercel: {
    teamId: '',
    teamName: '',
    webProjectId: '',
    adminProjectId: '',
    superadminProjectId: '',
    configProjectName: '',
    progress: {
      selectTeam: false,
      promptedForGithub: false,
      createWebProject: false,
      configureWebRootDirectory: false,
      createWebStagingEnvironment: false,
      linkWebGitHub: false,
      configureWebBranches: false,
      createWebInfisicalSyncProd: false,
      createWebInfisicalSyncStaging: false,
      createWebInfisicalSyncPreview: false,
      createAdminProject: false,
      configureAdminRootDirectory: false,
      createAdminStagingEnvironment: false,
      linkAdminGitHub: false,
      configureAdminBranches: false,
      createAdminInfisicalSyncProd: false,
      createAdminInfisicalSyncStaging: false,
      createAdminInfisicalSyncPreview: false,
      createSuperadminProject: false,
      configureSuperadminRootDirectory: false,
      createSuperadminStagingEnvironment: false,
      linkSuperadminGitHub: false,
      configureSuperadminBranches: false,
      createSuperadminInfisicalSyncProd: false,
      createSuperadminInfisicalSyncStaging: false,
      createSuperadminInfisicalSyncPreview: false,
      deployProduction: false,
    },
    error: '',
  },
} as const;

export type ProjectConfig = typeof projectConfig;
