// Auto-generated by scripts/generate-permissions-relation-targets.ts - do not edit
import type { AccessorName } from '@template/db';

export const relationTargets: Partial<Record<AccessorName, Partial<Record<string, AccessorName>>>> = {
  "account": {
    "user": "user"
  },
  "authProvider": {
    "organization": "organization"
  },
  "cronJob": {
    "createdBy": "user"
  },
  "customerRef": {
    "customerOrganization": "organization",
    "customerSpace": "space",
    "customerUser": "user",
    "providerSpace": "space"
  },
  "emailComponent": {
    "organization": "organization",
    "space": "space"
  },
  "emailTemplate": {
    "organization": "organization",
    "space": "space"
  },
  "inquiry": {
    "sourceOrganization": "organization",
    "sourceSpace": "space",
    "sourceUser": "user",
    "targetOrganization": "organization",
    "targetSpace": "space",
    "targetUser": "user"
  },
  "organization": {
    "authProviders": "authProvider",
    "emailComponents": "emailComponent",
    "emailTemplates": "emailTemplate",
    "inquiriesReceived": "inquiry",
    "inquiriesSent": "inquiry",
    "organizationUsers": "organizationUser",
    "providerRefs": "customerRef",
    "spaceUsers": "spaceUser",
    "spaces": "space",
    "tokens": "token",
    "webhookSubscriptions": "webhookSubscription"
  },
  "organizationUser": {
    "organization": "organization",
    "spaceUsers": "spaceUser",
    "tokens": "token",
    "user": "user"
  },
  "session": {
    "user": "user"
  },
  "space": {
    "customerRefs": "customerRef",
    "emailComponents": "emailComponent",
    "emailTemplates": "emailTemplate",
    "inquiriesReceived": "inquiry",
    "inquiriesSent": "inquiry",
    "organization": "organization",
    "providerRefs": "customerRef",
    "spaceUsers": "spaceUser",
    "tokens": "token",
    "webhookSubscriptions": "webhookSubscription"
  },
  "spaceUser": {
    "organization": "organization",
    "organizationUser": "organizationUser",
    "space": "space",
    "tokens": "token",
    "user": "user"
  },
  "token": {
    "organization": "organization",
    "organizationUser": "organizationUser",
    "space": "space",
    "spaceUser": "spaceUser",
    "user": "user"
  },
  "user": {
    "accounts": "account",
    "cronJobsCreated": "cronJob",
    "inquiriesReceived": "inquiry",
    "inquiriesSent": "inquiry",
    "organizationUsers": "organizationUser",
    "providerRefs": "customerRef",
    "sessions": "session",
    "spaceUsers": "spaceUser",
    "tokens": "token",
    "webhookSubscriptions": "webhookSubscription"
  },
  "webhookEvent": {
    "webhookSubscription": "webhookSubscription"
  },
  "webhookSubscription": {
    "organization": "organization",
    "space": "space",
    "user": "user",
    "webhookEvents": "webhookEvent"
  }
} as const;
