import { registerSoftDeleteScoper } from '@template/db';
import { registerAuditLogHook } from '#/hooks/auditLog/hook';
import { registerClearCacheHook } from '#/hooks/cache/hook';
import { registerContactRulesHook } from '#/hooks/contactRules/hook';
import { registerCronJobSyncHook } from '#/hooks/cronJobSync/hook';
import { registerEmailVersioningHook } from '#/hooks/emailVersioning/hook';
import { registerFeatureFlagHook } from '#/hooks/featureFlag/hook';
import { registerFeatureFlagChangedHook } from '#/hooks/featureFlagChanged/hook';
import { registerFeatureFlagVariantHook } from '#/hooks/featureFlagVariant/hook';
import { registerImmutableFieldsHook } from '#/hooks/immutableFields/hook';
import { registerLastLoginAtHook } from '#/hooks/lastLoginAt/hook';
import { registerOrderedListHook } from '#/hooks/orderedList/hook';
import { registerPlatformCustomerRefHook } from '#/hooks/platformCustomerRef/hook';
import { registerPreventHardDeleteHook } from '#/hooks/preventHardDelete/hook';
import { registerRuleReferenceReferencedHook } from '#/hooks/ruleReference/referencedHook';
import { registerRulesHook } from '#/hooks/rules/hook';
import { registerSegmentConditionsHook } from '#/hooks/segmentConditions/hook';
import { registerSegmentMemberOwnerHook } from '#/hooks/segmentMemberOwner/hook';
import { registerSegmentRuleReferencesHook } from '#/hooks/segmentRuleReferences/hook';
import { registerSoftDeleteCascadeHook } from '#/hooks/softDeleteCascade/hook';
import { registerTagOwnerCategoryHook } from '#/hooks/tagOwnerCategory/hook';
import { registerUserEmailInvariantHook } from '#/hooks/userEmail/hook';
import { registerUserEmailContactHook } from '#/hooks/userEmailContact/hook';
import { registerWebhookSubscriptionUrlHook } from '#/hooks/webhookSubscriptionUrl/hook';
import { registerWebhookHook } from '#/hooks/webhooks/hook';
import { liveIncludes, liveWhere } from '#/lib/prisma/softDeleteScope';

export const registerHooks = () => {
  registerSoftDeleteScoper({ liveWhere, liveIncludes });
  registerRulesHook();
  registerAuditLogHook();
  registerEmailVersioningHook();
  registerFeatureFlagHook();
  registerFeatureFlagChangedHook();
  registerFeatureFlagVariantHook();
  registerClearCacheHook();
  registerContactRulesHook();
  registerCronJobSyncHook();
  registerImmutableFieldsHook();
  registerLastLoginAtHook();
  registerOrderedListHook();
  registerPlatformCustomerRefHook();
  registerPreventHardDeleteHook();
  registerRuleReferenceReferencedHook();
  registerSegmentConditionsHook();
  registerSegmentMemberOwnerHook();
  registerSegmentRuleReferencesHook();
  registerSoftDeleteCascadeHook();
  registerTagOwnerCategoryHook();
  registerUserEmailInvariantHook();
  registerUserEmailContactHook();
  registerWebhookHook();
  registerWebhookSubscriptionUrlHook();
};
