import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getRuntimeDataModel } from '../src/utils/runtimeDataModel';

const inputDir = join(import.meta.dir, '../src/generated/zod/schemas/variants/input');
const pureDir = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure');
const outFile = join(import.meta.dir, '../src/generated/zod/scalarSchemas.gen.ts');
const indexFile = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure/index.ts');

const inputFiles = readdirSync(inputDir).filter((f) => f.endsWith('.input.ts'));
const pureFiles = readdirSync(pureDir).filter((f) => f.endsWith('.pure.ts'));

const inputModelNames = inputFiles.map((f) => f.replace('.input.ts', ''));
const pureModelNames = pureFiles.map((f) => f.replace('.pure.ts', ''));
const inputModelSet = new Set(inputModelNames);
const pureModelSet = new Set(pureModelNames);
const modelNames = [...new Set([...inputModelNames, ...pureModelNames])].sort();

// Get relation fields for each model from Prisma's runtimeDataModel
const dataModel = getRuntimeDataModel();
const modelRelations: Record<string, string[]> = {};

for (const modelName of modelNames) {
  const model = dataModel.models[modelName];
  if (model) {
    modelRelations[modelName] = model.fields.filter((f) => f.kind === 'object').map((f) => f.name);
  } else {
    modelRelations[modelName] = [];
  }
}

const inputImports = inputModelNames
  .sort()
  .map((m) => `import { ${m}InputSchema } from './schemas/variants/input/${m}.input';`)
  .join('\n');

const pureImports = pureModelNames
  .sort()
  .map((m) => `import { ${m}ModelSchema } from './schemas/variants/pure/${m}.pure';`)
  .join('\n');

const omit = (relations: string[]) =>
  relations.length === 0 ? '' : `.omit({ ${relations.map((r) => `${r}: true`).join(', ')} })`;

const schemaBuilds = modelNames
  .map((m) => {
    const rel = modelRelations[m];
    const lines: string[] = [];
    if (inputModelSet.has(m))
      lines.push(`export const ${m}ScalarInputSchema = ${m}InputSchema${omit(rel)};`);
    if (pureModelSet.has(m))
      lines.push(`export const ${m}ScalarSchema = ${m}ModelSchema${omit(rel)};`);
    return lines.join('\n');
  })
  .join('\n');

const output = `// Auto-generated by scripts/generate-scalar-schemas.ts - do not edit
${inputImports}
${pureImports}

${schemaBuilds}
`;

writeFileSync(outFile, output);

// Update the pure index to re-export scalar schemas
let indexContent = readFileSync(indexFile, 'utf-8');
const exportLine = "export * from '../../../scalarSchemas.gen';";
if (!indexContent.includes(exportLine)) {
  indexContent = `${indexContent.trimEnd()}\n${exportLine}\n`;
  writeFileSync(indexFile, indexContent);
}
