import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildPrismaMapV7 } from '@inixiative/prisma-map';

const generatedClientPath = join(import.meta.dir, '../src/generated/client');
const outFile = join(import.meta.dir, '../../permissions/src/rebac/prismaMap.gen.ts');

const rawPrismaMap = buildPrismaMapV7(generatedClientPath);

const sortedPrismaMap = Object.fromEntries(
  Object.entries(rawPrismaMap)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([modelName, model]) => [
      modelName,
      {
        dbName: model.dbName,
        fields: Object.fromEntries(Object.entries(model.fields).sort(([left], [right]) => left.localeCompare(right))),
      },
    ]),
);

const output = `// Auto-generated by scripts/generate-prisma-map.ts - do not edit
export const prismaMap = ${JSON.stringify(sortedPrismaMap, null, 2)} as const;
`;

writeFileSync(outFile, output);
