import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { prismaMap } from '@template/db/generated/prismaMap';

const inputDir = join(import.meta.dir, '../src/generated/zod/schemas/variants/input');
const pureDir = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure');
const outFile = join(import.meta.dir, '../src/generated/zod/scalarSchemas.gen.ts');
const indexFile = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure/index.ts');

const inputFiles = readdirSync(inputDir).filter((f) => f.endsWith('.input.ts'));
const pureFiles = readdirSync(pureDir).filter((f) => f.endsWith('.pure.ts'));

const inputModelNames = inputFiles.map((f) => f.replace('.input.ts', ''));
const pureModelNames = pureFiles.map((f) => f.replace('.pure.ts', ''));
const inputModelSet = new Set(inputModelNames);
const pureModelSet = new Set(pureModelNames);
const modelNames = [...new Set([...inputModelNames, ...pureModelNames])].sort();

// Relation fields per model, from the generated prismaMap (single source of truth).
const modelRelations: Record<string, string[]> = {};

for (const modelName of modelNames) {
  const model = prismaMap.models[modelName as keyof typeof prismaMap.models];
  modelRelations[modelName] = model
    ? Object.entries(model.fields)
        .filter(([, field]) => (field as { kind: string }).kind === 'object')
        .map(([name]) => name)
    : [];
}

const inputImports = inputModelNames
  .sort()
  .map((m) => `import { ${m}InputSchema } from './schemas/variants/input/${m}.input';`)
  .join('\n');

const pureImports = pureModelNames
  .sort()
  .map((m) => `import { ${m}ModelSchema } from './schemas/variants/pure/${m}.pure';`)
  .join('\n');

const omit = (relations: string[]) =>
  relations.length === 0 ? '' : `.omit({ ${relations.map((r) => `${r}: true`).join(', ')} })`;

// Detect default-having fields by diffing the two already-generated zod outputs:
// `objects/<Model>CreateInput.schema.ts` marks defaulted fields `.optional()`
// (Prisma create semantics), `variants/input/<Model>.input.ts` marks every
// non-nullable field required. The delta — excluding relations — is exactly
// the @id / @default / @updatedAt set. Used to chain `.partial({...})` on
// ScalarInputSchema so callers don't have to send server-assigned fields.
const optionalFieldsIn = (path: string): Set<string> => {
  const out = new Set<string>();
  for (const line of readFileSync(path, 'utf-8').split('\n')) {
    const m = line.match(/^\s+(\w+):\s+.+\.optional\(\)/);
    if (m) out.add(m[1]);
  }
  return out;
};

const objectsDir = join(import.meta.dir, '../src/generated/zod/schemas/objects');
const defaultedFieldsByModel: Record<string, string[]> = {};
for (const m of inputModelNames) {
  try {
    const createOpt = optionalFieldsIn(join(objectsDir, `${m}CreateInput.schema.ts`));
    const inputOpt = optionalFieldsIn(join(inputDir, `${m}.input.ts`));
    const relations = new Set(modelRelations[m]);
    defaultedFieldsByModel[m] = [...createOpt].filter((f) => !inputOpt.has(f) && !relations.has(f)).sort();
  } catch {
    defaultedFieldsByModel[m] = [];
  }
}
const partial = (defaulted: string[]) =>
  defaulted.length === 0 ? '' : `.partial({ ${defaulted.map((f) => `${f}: true`).join(', ')} })`;

const schemaBuilds = modelNames
  .map((m) => {
    const rel = modelRelations[m];
    const defaulted = defaultedFieldsByModel[m] ?? [];
    const lines: string[] = [];
    if (inputModelSet.has(m)) {
      lines.push(`export const ${m}ScalarInputSchema = ${m}InputSchema${omit(rel)}${partial(defaulted)};`);
    }
    if (pureModelSet.has(m)) lines.push(`export const ${m}ScalarSchema = ${m}ModelSchema${omit(rel)};`);
    return lines.join('\n');
  })
  .join('\n');

const output = `// Auto-generated by scripts/generate-scalar-schemas.ts - do not edit
${inputImports}
${pureImports}

${schemaBuilds}
`;

writeFileSync(outFile, output);

// Update the pure index to re-export scalar schemas
let indexContent = readFileSync(indexFile, 'utf-8');
const exportLine = "export * from '../../../scalarSchemas.gen';";
if (!indexContent.includes(exportLine)) {
  indexContent = `${indexContent.trimEnd()}\n${exportLine}\n`;
  writeFileSync(indexFile, indexContent);
}
