import { writeFileSync } from 'fs';
import { join } from 'path';
import { isModelName, toAccessor, type AccessorName } from '../src/utils/modelNames';
import { getRuntimeDataModel } from '../src/utils/runtimeDataModel';

const outFile = join(import.meta.dir, '../../permissions/src/rebac/relationTargetsGen.ts');
const dataModel = getRuntimeDataModel();

const relationTargets: Partial<Record<AccessorName, Partial<Record<string, AccessorName>>>> = {};

for (const [modelName, model] of Object.entries(dataModel.models)) {
  if (!isModelName(modelName)) continue;

  const sourceAccessor = toAccessor(modelName);
  const targets: Partial<Record<string, AccessorName>> = {};

  for (const field of model.fields) {
    if (field.kind !== 'object') continue;
    if (typeof field.type !== 'string' || !isModelName(field.type)) continue;
    targets[field.name] = toAccessor(field.type);
  }

  if (Object.keys(targets).length > 0) {
    relationTargets[sourceAccessor] = Object.fromEntries(
      Object.keys(targets)
        .sort()
        .map((key) => [key, targets[key as keyof typeof targets]]),
    ) as Partial<Record<string, AccessorName>>;
  }
}

const sortedRelationTargets = Object.fromEntries(
  Object.keys(relationTargets)
    .sort()
    .map((key) => [key, relationTargets[key as keyof typeof relationTargets]]),
);

const output = `// Auto-generated by scripts/generatePermissionsRelationTargets.ts - do not edit
import type { AccessorName } from '@template/db';

export const relationTargets: Partial<Record<AccessorName, Partial<Record<string, AccessorName>>>> = ${JSON.stringify(
  sortedRelationTargets,
  null,
  2,
)} as const;
`;

writeFileSync(outFile, output);
console.log(`Generated permissions relation targets: ${outFile}`);
