import { readdirSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { getRuntimeDataModel } from '../src/utils/runtimeDataModel';

const pureDir = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure');
const outFile = join(import.meta.dir, '../src/generated/zod/scalarSchemas.ts');
const indexFile = join(import.meta.dir, '../src/generated/zod/schemas/variants/pure/index.ts');

const files = readdirSync(pureDir).filter((f) => f.endsWith('.pure.ts'));
const modelNames = files.map((f) => f.replace('.pure.ts', ''));

// Get relation fields for each model from Prisma's runtimeDataModel
const dataModel = getRuntimeDataModel();
const modelRelations: Record<string, string[]> = {};

for (const modelName of modelNames) {
  const model = dataModel.models[modelName];
  if (model) {
    modelRelations[modelName] = model.fields
      .filter((f) => f.kind === 'object')
      .map((f) => f.name);
  } else {
    modelRelations[modelName] = [];
  }
}

const imports = modelNames
  .map((m) => `import { ${m}ModelSchema } from './schemas/variants/pure/${m}.pure';`)
  .join('\n');

const schemaBuilds = modelNames
  .map((m) => {
    const relations = modelRelations[m];
    if (relations.length === 0) {
      return `export const ${m}ScalarSchema = ${m}ModelSchema;`;
    }
    const omitFields = relations.map((r) => `'${r}'`).join(', ');
    return `export const ${m}ScalarSchema = ${m}ModelSchema.omit({ ${relations.map((r) => `${r}: true`).join(', ')} });`;
  })
  .join('\n');

const output = `// Auto-generated by scripts/generateScalarSchemas.ts - do not edit
${imports}

${schemaBuilds}
`;

writeFileSync(outFile, output);

// Update the pure index to re-export scalar schemas
let indexContent = readFileSync(indexFile, 'utf-8');
const exportLine = "export * from '../../../scalarSchemas';";
if (!indexContent.includes(exportLine)) {
  indexContent = indexContent.trimEnd() + '\n' + exportLine + '\n';
  writeFileSync(indexFile, indexContent);
}

console.log(`Generated ${modelNames.length} scalar schemas`);
