/**
 * @atlas
 * @kind utils
 * @partOf infrastructure:prisma
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildPrismaMapV7 } from '@inixiative/prisma-map';

const generatedClientPath = join(import.meta.dir, '../src/generated/client');
const outFile = join(import.meta.dir, '../src/generated/prismaMap.gen.ts');

const rawPrismaMap = buildPrismaMapV7(generatedClientPath);

const sortedModels = Object.fromEntries(
  Object.entries(rawPrismaMap)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([modelName, model]) => [
      modelName,
      {
        dbName: model.dbName,
        fields: Object.fromEntries(Object.entries(model.fields).sort(([left], [right]) => left.localeCompare(right))),
      },
    ]),
);

// Enum registry: walk every enum-kind field and collect unique values per type.
// json-rules 2.1 FieldMap shape requires top-level `enums: Record<enumName, readonly string[]>`.
const enums: Record<string, readonly string[]> = {};
for (const model of Object.values(sortedModels)) {
  for (const field of Object.values(model.fields) as { kind: string; type: string; values?: string[] }[]) {
    if (field.kind === 'enum' && field.values && !enums[field.type]) {
      enums[field.type] = [...field.values].sort();
    }
  }
}
const sortedEnums = Object.fromEntries(Object.entries(enums).sort(([left], [right]) => left.localeCompare(right)));

const output = `// Auto-generated by scripts/generatePrismaMap.ts - do not edit
export const prismaMap = ${JSON.stringify({ models: sortedModels, enums: sortedEnums }, null, 2)} as const;
`;

writeFileSync(outFile, output);
