import type { ContactType } from '@template/db/generated/client/enums';
import {
  blueskyDef,
  type ContactTypeDef,
  discordDef,
  emailDef,
  facebookDef,
  githubDef,
  instagramDef,
  lineDef,
  linkedinDef,
  mastodonDef,
  phoneDef,
  redditDef,
  signalDef,
  skypeDef,
  telegramDef,
  threadsDef,
  tiktokDef,
  twitterDef,
  viberDef,
  websiteDef,
  wechatDef,
  whatsappDef,
  youtubeDef,
} from '@template/shared/contact/defs';

// biome-ignore lint/suspicious/noExplicitAny: per-type generics are heterogeneous; consumers narrow via ContactType.
export const ContactRegistry: Record<ContactType, ContactTypeDef<any, any>> = {
  phone: phoneDef,
  email: emailDef,
  website: websiteDef,
  linkedin: linkedinDef,
  github: githubDef,
  twitter: twitterDef,
  whatsapp: whatsappDef,
  telegram: telegramDef,
  discord: discordDef,
  instagram: instagramDef,
  facebook: facebookDef,
  youtube: youtubeDef,
  tiktok: tiktokDef,
  bluesky: blueskyDef,
  threads: threadsDef,
  reddit: redditDef,
  signal: signalDef,
  mastodon: mastodonDef,
  line: lineDef,
  wechat: wechatDef,
  viber: viberDef,
  skype: skypeDef,
};
