import type { EmailTemplate } from '../../src/generated/client/client';
import type { SeedFile } from '../seed';

export const emailTemplateSeeds: SeedFile<EmailTemplate> = {
  model: 'emailTemplate',
  updateOmitFields: ['createdAt'],
  records: [
    {
      id: '01936d42-ec00-7000-8000-000000000010',
      slug: 'email-verification',
      name: 'Email Verification',
      locale: 'en',
      ownerModel: 'default',
      category: 'system',
      inheritToSpaces: true,
      componentRefs: ['system-header', 'system-button', 'system-footer'],
      subject: 'Verify your email address',
      mjml: [
        '<mjml>',
        '  <mj-body background-color="#f9fafb">',
        '    {{#component:system-header}}{{/component:system-header}}',
        '    <mj-section padding="20px 0">',
        '      <mj-column>',
        '        <mj-text font-size="16px" color="#111827" line-height="1.5">',
        '          Hi {{recipient.name}},',
        '        </mj-text>',
        '        <mj-text font-size="16px" color="#374151" line-height="1.5">',
        '          Please verify your email address to complete your account setup.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-button}}{{/component:system-button}}',
        '    <mj-section padding="0">',
        '      <mj-column>',
        '        <mj-text font-size="13px" color="#6b7280" line-height="1.5">',
        '          If you did not create an account, you can safely ignore this email.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-footer}}{{/component:system-footer}}',
        '  </mj-body>',
        '</mjml>',
      ].join('\n'),
    },
    {
      id: '01936d42-ec00-7000-8000-000000000011',
      slug: 'org-invitation',
      name: 'Organization Invitation',
      locale: 'en',
      ownerModel: 'default',
      category: 'system',
      inheritToSpaces: true,
      componentRefs: ['system-header', 'system-button', 'system-footer'],
      subject: "You've been invited to {{data.organizationName}}",
      mjml: [
        '<mjml>',
        '  <mj-body background-color="#f9fafb">',
        '    {{#component:system-header}}{{/component:system-header}}',
        '    <mj-section padding="20px 0">',
        '      <mj-column>',
        '        <mj-text font-size="16px" color="#111827" line-height="1.5">',
        '          Hi {{recipient.name}},',
        '        </mj-text>',
        '        <mj-text font-size="16px" color="#374151" line-height="1.5">',
        '          {{data.inviterName}} has invited you to join',
        '          <strong>{{data.organizationName}}</strong> as a {{data.role}}.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-button}}{{/component:system-button}}',
        '    <mj-section padding="0">',
        '      <mj-column>',
        '        <mj-text font-size="13px" color="#6b7280" line-height="1.5">',
        '          This invitation will expire in 30 days. If you did not expect this invitation, you can safely ignore this email.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-footer}}{{/component:system-footer}}',
        '  </mj-body>',
        '</mjml>',
      ].join('\n'),
    },
  ],
};
