/**
 * @atlas
 * @kind seed
 * @partOf infrastructure:prisma
 * @uses none
 */
import type { EmailTemplate } from '../../src/generated/client/client';
import type { SeedFile } from '../seed';

export const emailTemplateSeeds: SeedFile<EmailTemplate> = {
  model: 'emailTemplate',
  updateOmitFields: ['createdAt'],
  records: [
    {
      id: '01936d42-ec00-7000-8000-000000000010',
      slug: 'email-verification',
      name: 'Email Verification',
      locale: 'en',
      ownerModel: 'default',
      category: 'system',
      inheritToSpaces: true,
      componentRefs: ['system-header', 'system-footer'],
      subject: 'Verify your email address',
      mjml: [
        '<mjml>',
        '  <mj-body background-color="#f9fafb">',
        '    {{#component:system-header}}{{/component:system-header}}',
        '    <mj-section padding="20px 0">',
        '      <mj-column>',
        '        <mj-text font-size="16px" color="#111827" line-height="1.5">',
        '          Hi {{recipient.name}},',
        '        </mj-text>',
        '        <mj-text font-size="16px" color="#374151" line-height="1.5">',
        '          Please verify your email address to complete your account setup.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    <mj-section padding="10px 0">',
        '      <mj-column>',
        '        <mj-button href="{{data.verificationUrl}}" background-color="#2563eb" color="#ffffff" font-size="16px" border-radius="6px" inner-padding="12px 24px">',
        '          Verify Email',
        '        </mj-button>',
        '      </mj-column>',
        '    </mj-section>',
        '    <mj-section padding="0">',
        '      <mj-column>',
        '        <mj-text font-size="13px" color="#6b7280" line-height="1.5">',
        '          If you did not create an account, you can safely ignore this email.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-footer}}{{/component:system-footer}}',
        '  </mj-body>',
        '</mjml>',
      ].join('\n'),
    },
    {
      id: '01936d42-ec00-7000-8000-000000000011',
      slug: 'inquiry-invite-organization-user',
      name: 'Organization Invitation',
      locale: 'en',
      ownerModel: 'default',
      category: 'system',
      inheritToSpaces: true,
      componentRefs: ['system-header', 'system-footer'],
      subject: "You've been invited to {{data.sourceOrganization.name}}",
      mjml: [
        '<mjml>',
        '  <mj-body background-color="#f9fafb">',
        '    {{#component:system-header}}{{/component:system-header}}',
        '    <mj-section padding="20px 0">',
        '      <mj-column>',
        '        <mj-text font-size="16px" color="#111827" line-height="1.5">',
        '          Hi {{recipient.name}},',
        '        </mj-text>',
        '        <mj-text font-size="16px" color="#374151" line-height="1.5">',
        "          You've been invited to join <strong>{{data.sourceOrganization.name}}</strong> as a {{data.content.role}}.",
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    <mj-section padding="10px 0">',
        '      <mj-column>',
        '        <mj-button href="{{sender.webUrl}}/invitations/{{data.id}}" background-color="#2563eb" color="#ffffff" font-size="16px" border-radius="6px" inner-padding="12px 24px">',
        '          Accept Invitation',
        '        </mj-button>',
        '      </mj-column>',
        '    </mj-section>',
        '    <mj-section padding="0">',
        '      <mj-column>',
        '        <mj-text font-size="13px" color="#6b7280" line-height="1.5">',
        '          This invitation will expire in 30 days. If you did not expect this invitation, you can safely ignore this email.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-footer}}{{/component:system-footer}}',
        '  </mj-body>',
        '</mjml>',
      ].join('\n'),
    },
    {
      id: '01936d42-ec00-7000-8000-000000000012',
      slug: 'welcome',
      name: 'Welcome',
      locale: 'en',
      ownerModel: 'default',
      category: 'system',
      inheritToSpaces: true,
      componentRefs: ['system-header', 'system-footer'],
      subject: 'Welcome to {{sender.platformName}}',
      mjml: [
        '<mjml>',
        '  <mj-body background-color="#f9fafb">',
        '    {{#component:system-header}}{{/component:system-header}}',
        '    <mj-section padding="20px 0">',
        '      <mj-column>',
        '        <mj-text font-size="16px" color="#111827" line-height="1.5">',
        '          Hi {{recipient.name}},',
        '        </mj-text>',
        '        <mj-text font-size="16px" color="#374151" line-height="1.5">',
        '          Welcome! Your account has been created. You can sign in at any time to get started.',
        '        </mj-text>',
        '      </mj-column>',
        '    </mj-section>',
        '    {{#component:system-footer}}{{/component:system-footer}}',
        '  </mj-body>',
        '</mjml>',
      ].join('\n'),
    },
  ],
};
